# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrackIT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrackIT
 pod 'lottie-ios'
pod 'Firebase/Firestore'

# Optionally, include the Swift extensions if you're using Swift.
pod 'FirebaseFirestoreSwift'
  target 'TrackITTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrackITUITests' do
    # Pods for testing
  end

end
