# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrackIT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrackIT
 pod 'lottie-ios'
pod 'Firebase/Firestore'

pod 'Alamofire', '~> 4.5'
    #Auto Layout library
    pod 'SnapKit', '~> 4.0.0'
    #library for downloading and caching images from API
    #pod 'Kingfisher', '~> 3.0'
    #Send Message TextInput
    pod 'Toolbar'
    #Messages TableView
    pod 'ReverseExtension'
    #Promise
    pod 'PromiseKit', '~> 4.4'

# Optionally, include the Swift extensions if you're using Swift.
pod 'FirebaseFirestoreSwift'
  target 'TrackITTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrackITUITests' do
    # Pods for testing
  end

end
